"""Lay out big single-line captions above the speaker's head, partly hidden
behind it (reference: big title at the top, hair overlapping the letters).

usage: make_pages_top.py words.json matte.mp4 ffmpeg out.ts bebas.woff
"""
import json, re, subprocess, sys
import numpy as np
from fontTools.ttLib import TTFont

words_path, matte_path, ffmpeg, out_ts, font_path = sys.argv[1:6]
FPS, W, H, N = 24, 1080, 1920, 720
CUTS = [0, 240, 480, 720]

SIDE_MARGIN = 50      # px left/right
TOP_MARGIN = 130      # keep clear of the phone status bar / app header
OVERLAP = 0.30        # share of the cap height hidden behind the head
MAX_FONT = 380
MAX_CHARS = 11        # per page (one line)

font = TTFont(font_path)
cmap, hmtx, upm = font.getBestCmap(), font["hmtx"], font["head"].unitsPerEm
CAP = font["OS/2"].sCapHeight / upm
ASC, DESC = font["hhea"].ascent / upm, -font["hhea"].descent / upm
BASELINE_IN_LINEBOX = (1 - (ASC + DESC)) / 2 + ASC   # with CSS line-height: 1

def width_em(text, gap_em=0.25):
    em = 0.0
    for ch in text:
        if ch == " ":
            em += gap_em
            continue
        g = cmap.get(ord(ch))
        em += (hmtx[g][0] if g else upm * 0.5) / upm
    return em

def clean(t):
    return re.sub(r"[.,;:]", "", t).upper()

FIXES = {(14.42, "qué"): "que"}
words = []
for w in json.load(open(words_path)):
    text = FIXES.get((round(w["start"], 2), w["text"]), w["text"])
    start, end = w["start"], w["end"]
    if end - start > 0.6:
        start = end - 0.45
    words.append({"text": text, "start": start, "end": end})

def label(p):
    return " ".join(clean(x["text"]) for x in p)

pages, cur = [], []
for i, w in enumerate(words):
    cur.append(w)
    nxt = words[i + 1] if i + 1 < len(words) else None
    if (nxt is None or re.search(r"[.,?!]$", w["text"]) or nxt["start"] - w["end"] > 0.35
            or len(cur) >= 2 or len(label(cur + [nxt])) > MAX_CHARS):
        pages.append(cur); cur = []

merged, i = [], 0
while i < len(pages):                 # merge flash pages (< 7 frames) into the next one
    p = pages[i]
    if i + 1 < len(pages) and (pages[i + 1][0]["start"] - p[0]["start"]) * FPS < 7 \
            and len(label(p + pages[i + 1])) <= 13:
        pages[i + 1] = p + pages[i + 1]; i += 1; continue
    merged.append(p); i += 1
pages = merged

proc = subprocess.run([ffmpeg, "-v", "error", "-i", matte_path, "-vf", "scale=270:480",
                       "-f", "rawvideo", "-pix_fmt", "gray", "-"], capture_output=True, check=True)
m = np.frombuffer(proc.stdout, np.uint8).reshape(-1, 480, 270) > 100
head_top = np.array([np.where(f.sum(axis=1) >= 6)[0][0] * 4 if f.any() else 400 for f in m], dtype=float)

out = []
for i, p in enumerate(pages):
    start = p[0]["start"]
    nxt_start = pages[i + 1][0]["start"] if i + 1 < len(pages) else 30.0
    end = min(nxt_start, p[-1]["end"] + 0.6)
    sf, ef = round(start * FPS), round(end * FPS)
    clip_hi = min(c for c in CUTS if c > sf)
    top_y = float(np.median(head_top[sf:min(ef, clip_hi)]))

    text = label(p)
    fs_width = (W - 2 * SIDE_MARGIN) / width_em(text)
    fs_height = (top_y - TOP_MARGIN) / (CAP * (1 - OVERLAP))
    fs = min(fs_width, fs_height, MAX_FONT)
    baseline = top_y + OVERLAP * CAP * fs
    out.append({
        "startFrame": sf, "endFrame": ef, "fontSize": round(fs),
        "top": round(baseline - BASELINE_IN_LINEBOX * fs),
        "words": [{"text": clean(x["text"]), "startFrame": round(x["start"] * FPS)} for x in p],
    })

with open(out_ts, "w") as fh:
    fh.write("// Generated by scripts/behind-captions/make_pages_top.py from the Whisper\n"
             "// transcript and the person matte. Do not edit by hand.\n")
    fh.write("export type CaptionWord = { text: string; startFrame: number };\n")
    fh.write("export type CaptionPage = {\n  startFrame: number;\n  endFrame: number;\n"
             "  fontSize: number;\n  top: number;\n  words: CaptionWord[];\n};\n\n")
    fh.write("export const PAGES: CaptionPage[] = " + json.dumps(out, ensure_ascii=False, indent=2) + ";\n")
for o in out:
    print(f"{o['startFrame']:4d}-{o['endFrame']:4d}  top={o['top']:4d} fs={o['fontSize']:3d}  {' '.join(w['text'] for w in o['words'])}")
