// Generated by make_reel_data.py from the transcript and jump-cut list.
// SEGMENTS: [sourceStart, sourceEnd] seconds of k_joined.mp4 kept, in order.
// WORDS: times in seconds on the edited timeline.

export const DURATION = 49.66;

export const SEGMENTS: [number, number][] = [[0.33, 2.71], [3.19, 3.81], [4.57, 8.13], [9.17, 10.05], [10.25, 12.45], [12.71, 14.27], [14.63, 18.35], [20.07, 22.13], [22.39, 29.39], [30.25, 32.65], [33.03, 34.53], [34.73, 36.15], [36.77, 38.31], [38.87, 39.75], [39.99, 45.77], [45.91, 50.07], [50.19, 52.95], [53.41, 55.35], [55.81, 57.09], [57.43, 59.45]];

export const WORDS: { text: string; start: number; end: number }[] = [
 {
  "text": "Vale,",
  "start": 0.0,
  "end": 0.27
 },
 {
  "text": "Claude",
  "start": 0.47,
  "end": 0.63
 },
 {
  "text": "acaba",
  "start": 0.63,
  "end": 1.01
 },
 {
  "text": "de",
  "start": 1.01,
  "end": 1.21
 },
 {
  "text": "cargarse",
  "start": 1.21,
  "end": 1.65
 },
 {
  "text": "Instagram.",
  "start": 1.65,
  "end": 2.09
 },
 {
  "text": "En",
  "start": 2.38,
  "end": 2.55
 },
 {
  "text": "serio,",
  "start": 2.55,
  "end": 2.81
 },
 {
  "text": "lo",
  "start": 3.0,
  "end": 3.17
 },
 {
  "text": "conectas",
  "start": 3.17,
  "end": 3.57
 },
 {
  "text": "a",
  "start": 3.57,
  "end": 3.65
 },
 {
  "text": "tu",
  "start": 3.65,
  "end": 3.75
 },
 {
  "text": "cuenta",
  "start": 3.75,
  "end": 4.05
 },
 {
  "text": "y",
  "start": 4.05,
  "end": 4.49
 },
 {
  "text": "te",
  "start": 4.49,
  "end": 4.59
 },
 {
  "text": "la",
  "start": 4.59,
  "end": 4.69
 },
 {
  "text": "lleva",
  "start": 4.69,
  "end": 4.89
 },
 {
  "text": "entera,",
  "start": 4.89,
  "end": 5.35
 },
 {
  "text": "de",
  "start": 5.63,
  "end": 5.67
 },
 {
  "text": "principio",
  "start": 5.67,
  "end": 5.99
 },
 {
  "text": "a",
  "start": 5.99,
  "end": 6.23
 },
 {
  "text": "fin.",
  "start": 6.23,
  "end": 6.41
 },
 {
  "text": "Y",
  "start": 6.56,
  "end": 6.69
 },
 {
  "text": "lo",
  "start": 6.69,
  "end": 6.81
 },
 {
  "text": "hace",
  "start": 6.81,
  "end": 6.95
 },
 {
  "text": "todo",
  "start": 6.95,
  "end": 7.23
 },
 {
  "text": "Con",
  "start": 7.39,
  "end": 7.63
 },
 {
  "text": "este",
  "start": 7.63,
  "end": 7.81
 },
 {
  "text": "pack",
  "start": 7.81,
  "end": 8.07
 },
 {
  "text": "gratis",
  "start": 8.07,
  "end": 8.55
 },
 {
  "text": "de",
  "start": 8.55,
  "end": 8.69
 },
 {
  "text": "13",
  "start": 8.69,
  "end": 8.99
 },
 {
  "text": "skills",
  "start": 8.99,
  "end": 9.35
 },
 {
  "text": "Instagram",
  "start": 9.35,
  "end": 10.07
 },
 {
  "text": "Agent",
  "start": 10.07,
  "end": 10.57
 },
 {
  "text": "Skill",
  "start": 10.57,
  "end": 10.99
 },
 {
  "text": "Cada",
  "start": 10.99,
  "end": 11.39
 },
 {
  "text": "una",
  "start": 11.39,
  "end": 11.69
 },
 {
  "text": "hace",
  "start": 11.69,
  "end": 12.15
 },
 {
  "text": "algo",
  "start": 12.15,
  "end": 12.37
 },
 {
  "text": "distinto",
  "start": 12.37,
  "end": 12.89
 },
 {
  "text": "y",
  "start": 12.89,
  "end": 13.33
 },
 {
  "text": "la",
  "start": 13.33,
  "end": 13.45
 },
 {
  "text": "última",
  "start": 13.45,
  "end": 13.81
 },
 {
  "text": "que",
  "start": 13.81,
  "end": 14.01
 },
 {
  "text": "te",
  "start": 14.01,
  "end": 14.13
 },
 {
  "text": "voy",
  "start": 14.13,
  "end": 14.23
 },
 {
  "text": "a",
  "start": 14.23,
  "end": 14.33
 },
 {
  "text": "enseñar",
  "start": 14.33,
  "end": 14.77
 },
 {
  "text": "es,",
  "start": 14.92,
  "end": 15.19
 },
 {
  "text": "con",
  "start": 15.23,
  "end": 15.57
 },
 {
  "text": "diferencia,",
  "start": 15.57,
  "end": 16.07
 },
 {
  "text": "la",
  "start": 16.45,
  "end": 16.53
 },
 {
  "text": "mejor.",
  "start": 16.53,
  "end": 16.85
 },
 {
  "text": "Le",
  "start": 17.05,
  "end": 17.15
 },
 {
  "text": "pides",
  "start": 17.15,
  "end": 17.33
 },
 {
  "text": "un",
  "start": 17.33,
  "end": 17.55
 },
 {
  "text": "reel",
  "start": 17.55,
  "end": 17.79
 },
 {
  "text": "y",
  "start": 17.79,
  "end": 18.25
 },
 {
  "text": "te",
  "start": 18.25,
  "end": 18.35
 },
 {
  "text": "escribe",
  "start": 18.35,
  "end": 18.61
 },
 {
  "text": "el",
  "start": 18.61,
  "end": 18.79
 },
 {
  "text": "guion",
  "start": 18.79,
  "end": 18.95
 },
 {
  "text": "entero",
  "start": 18.95,
  "end": 19.37
 },
 {
  "text": "con",
  "start": 19.37,
  "end": 19.89
 },
 {
  "text": "26",
  "start": 19.89,
  "end": 20.39
 },
 {
  "text": "fórmulas",
  "start": 20.39,
  "end": 20.91
 },
 {
  "text": "de",
  "start": 20.91,
  "end": 21.05
 },
 {
  "text": "gancho",
  "start": 21.05,
  "end": 21.37
 },
 {
  "text": "probadas",
  "start": 21.37,
  "end": 21.83
 },
 {
  "text": "y",
  "start": 21.83,
  "end": 22.39
 },
 {
  "text": "encima",
  "start": 22.39,
  "end": 22.79
 },
 {
  "text": "te",
  "start": 22.79,
  "end": 23.25
 },
 {
  "text": "responde",
  "start": 23.25,
  "end": 23.85
 },
 {
  "text": "en",
  "start": 23.98,
  "end": 24.13
 },
 {
  "text": "los",
  "start": 24.13,
  "end": 24.23
 },
 {
  "text": "comentarios",
  "start": 24.23,
  "end": 24.77
 },
 {
  "text": "y",
  "start": 24.77,
  "end": 25.23
 },
 {
  "text": "hasta",
  "start": 25.23,
  "end": 25.41
 },
 {
  "text": "comenta",
  "start": 25.41,
  "end": 25.81
 },
 {
  "text": "por",
  "start": 25.81,
  "end": 26.01
 },
 {
  "text": "ti.",
  "start": 26.01,
  "end": 26.25
 },
 {
  "text": "Te",
  "start": 26.38,
  "end": 26.53
 },
 {
  "text": "puntúa",
  "start": 26.53,
  "end": 26.97
 },
 {
  "text": "el",
  "start": 26.97,
  "end": 27.11
 },
 {
  "text": "perfil,",
  "start": 27.11,
  "end": 27.67
 },
 {
  "text": "te",
  "start": 27.91,
  "end": 28.03
 },
 {
  "text": "reescribe",
  "start": 28.03,
  "end": 28.57
 },
 {
  "text": "la",
  "start": 28.57,
  "end": 28.79
 },
 {
  "text": "bio",
  "start": 28.79,
  "end": 29.05
 },
 {
  "text": "y",
  "start": 29.05,
  "end": 29.47
 },
 {
  "text": "te",
  "start": 29.47,
  "end": 29.61
 },
 {
  "text": "planifica",
  "start": 29.61,
  "end": 30.13
 },
 {
  "text": "la",
  "start": 30.13,
  "end": 30.29
 },
 {
  "text": "semana,",
  "start": 30.29,
  "end": 30.69
 },
 {
  "text": "pero",
  "start": 30.84,
  "end": 31.03
 },
 {
  "text": "la",
  "start": 31.03,
  "end": 31.17
 },
 {
  "text": "mejor",
  "start": 31.17,
  "end": 31.49
 },
 {
  "text": "es",
  "start": 31.73,
  "end": 32.39
 },
 {
  "text": "la",
  "start": 32.39,
  "end": 32.53
 },
 {
  "text": "de",
  "start": 32.53,
  "end": 32.67
 },
 {
  "text": "viralidad.",
  "start": 32.67,
  "end": 33.29
 },
 {
  "text": "Encuentra",
  "start": 33.67,
  "end": 34.19
 },
 {
  "text": "los",
  "start": 34.19,
  "end": 34.35
 },
 {
  "text": "reels",
  "start": 34.35,
  "end": 34.65
 },
 {
  "text": "que",
  "start": 34.65,
  "end": 34.91
 },
 {
  "text": "petan,",
  "start": 34.91,
  "end": 35.39
 },
 {
  "text": "te",
  "start": 35.77,
  "end": 35.93
 },
 {
  "text": "dice",
  "start": 35.93,
  "end": 36.15
 },
 {
  "text": "por",
  "start": 36.15,
  "end": 36.41
 },
 {
  "text": "qué",
  "start": 36.41,
  "end": 36.55
 },
 {
  "text": "funcionan",
  "start": 36.55,
  "end": 37.27
 },
 {
  "text": "y",
  "start": 37.27,
  "end": 37.73
 },
 {
  "text": "te",
  "start": 37.73,
  "end": 38.19
 },
 {
  "text": "los",
  "start": 38.19,
  "end": 38.31
 },
 {
  "text": "convierte",
  "start": 38.31,
  "end": 38.77
 },
 {
  "text": "en",
  "start": 38.77,
  "end": 39.23
 },
 {
  "text": "guiones",
  "start": 39.23,
  "end": 39.57
 },
 {
  "text": "con",
  "start": 39.57,
  "end": 40.17
 },
 {
  "text": "tu",
  "start": 40.17,
  "end": 40.33
 },
 {
  "text": "voz.",
  "start": 40.33,
  "end": 40.61
 },
 {
  "text": "Así",
  "start": 41.01,
  "end": 41.25
 },
 {
  "text": "que",
  "start": 41.25,
  "end": 41.49
 },
 {
  "text": "Olvídate",
  "start": 41.59,
  "end": 42.15
 },
 {
  "text": "de",
  "start": 42.15,
  "end": 42.33
 },
 {
  "text": "quedarte",
  "start": 42.33,
  "end": 42.67
 },
 {
  "text": "en",
  "start": 42.67,
  "end": 42.85
 },
 {
  "text": "blanco",
  "start": 42.85,
  "end": 43.17
 },
 {
  "text": "pensando",
  "start": 43.17,
  "end": 43.61
 },
 {
  "text": "qué",
  "start": 43.61,
  "end": 43.87
 },
 {
  "text": "subir.",
  "start": 43.87,
  "end": 44.19
 },
 {
  "text": "Se",
  "start": 44.42,
  "end": 44.63
 },
 {
  "text": "instala",
  "start": 44.63,
  "end": 44.93
 },
 {
  "text": "pegando",
  "start": 44.93,
  "end": 45.33
 },
 {
  "text": "un",
  "start": 45.33,
  "end": 45.47
 },
 {
  "text": "link",
  "start": 45.47,
  "end": 45.69
 },
 {
  "text": "en",
  "start": 45.69,
  "end": 45.89
 },
 {
  "text": "Claude.",
  "start": 45.89,
  "end": 46.19
 },
 {
  "text": "¿Quieres",
  "start": 46.36,
  "end": 46.65
 },
 {
  "text": "la",
  "start": 46.65,
  "end": 46.75
 },
 {
  "text": "guía",
  "start": 46.75,
  "end": 46.91
 },
 {
  "text": "completa?",
  "start": 46.91,
  "end": 47.29
 },
 {
  "text": "Coméntame",
  "start": 47.67,
  "end": 48.13
 },
 {
  "text": "AGENTE",
  "start": 48.13,
  "end": 48.69
 },
 {
  "text": "y",
  "start": 48.69,
  "end": 49.05
 },
 {
  "text": "te",
  "start": 49.05,
  "end": 49.15
 },
 {
  "text": "la",
  "start": 49.15,
  "end": 49.25
 },
 {
  "text": "paso.",
  "start": 49.25,
  "end": 49.49
 }
];
