// Generated by scripts/behind-captions/make_pages_3d.py from the Whisper
// transcript and the person matte. Do not edit by hand.
export type CaptionWord = { text: string; startFrame: number };
export type CaptionPage = {
  startFrame: number;
  endFrame: number;
  fontSize: number;
  top: number;
  lines: CaptionWord[][];
};

export const PAGES: CaptionPage[] = [
  {
    "startFrame": 0,
    "endFrame": 21,
    "fontSize": 275,
    "top": 120,
    "lines": [
      [
        {
          "text": "Vale",
          "startFrame": 0
        }
      ],
      [
        {
          "text": "dicen",
          "startFrame": 12
        }
      ]
    ]
  },
  {
    "startFrame": 21,
    "endFrame": 52,
    "fontSize": 285,
    "top": 120,
    "lines": [
      [
        {
          "text": "que",
          "startFrame": 21
        }
      ],
      [
        {
          "text": "soy",
          "startFrame": 25
        },
        {
          "text": "IA",
          "startFrame": 31
        }
      ]
    ]
  },
  {
    "startFrame": 52,
    "endFrame": 82,
    "fontSize": 187,
    "top": 130,
    "lines": [
      [
        {
          "text": "pues",
          "startFrame": 52
        },
        {
          "text": "os",
          "startFrame": 58
        }
      ],
      [
        {
          "text": "reto",
          "startFrame": 62
        }
      ]
    ]
  },
  {
    "startFrame": 82,
    "endFrame": 98,
    "fontSize": 155,
    "top": 150,
    "lines": [
      [
        {
          "text": "si",
          "startFrame": 82
        }
      ],
      [
        {
          "text": "encontráis",
          "startFrame": 85
        }
      ]
    ]
  },
  {
    "startFrame": 98,
    "endFrame": 111,
    "fontSize": 226,
    "top": 230,
    "lines": [
      [
        {
          "text": "el",
          "startFrame": 98
        },
        {
          "text": "fallo",
          "startFrame": 101
        }
      ]
    ]
  },
  {
    "startFrame": 111,
    "endFrame": 135,
    "fontSize": 163,
    "top": 130,
    "lines": [
      [
        {
          "text": "que",
          "startFrame": 111
        },
        {
          "text": "lo",
          "startFrame": 115
        }
      ],
      [
        {
          "text": "demuestra",
          "startFrame": 117
        }
      ]
    ]
  },
  {
    "startFrame": 135,
    "endFrame": 152,
    "fontSize": 252,
    "top": 200,
    "lines": [
      [
        {
          "text": "os",
          "startFrame": 135
        },
        {
          "text": "sigo",
          "startFrame": 146
        }
      ]
    ]
  },
  {
    "startFrame": 152,
    "endFrame": 171,
    "fontSize": 184,
    "top": 120,
    "lines": [
      [
        {
          "text": "yo",
          "startFrame": 152
        },
        {
          "text": "a",
          "startFrame": 156
        }
      ],
      [
        {
          "text": "vosotros",
          "startFrame": 157
        }
      ]
    ]
  },
  {
    "startFrame": 171,
    "endFrame": 179,
    "fontSize": 252,
    "top": 190,
    "lines": [
      [
        {
          "text": "os",
          "startFrame": 171
        },
        {
          "text": "sigo",
          "startFrame": 174
        }
      ]
    ]
  },
  {
    "startFrame": 179,
    "endFrame": 204,
    "fontSize": 184,
    "top": 130,
    "lines": [
      [
        {
          "text": "yo",
          "startFrame": 179
        },
        {
          "text": "a",
          "startFrame": 181
        }
      ],
      [
        {
          "text": "vosotros",
          "startFrame": 184
        }
      ]
    ]
  },
  {
    "startFrame": 204,
    "endFrame": 220,
    "fontSize": 207,
    "top": 160,
    "lines": [
      [
        {
          "text": "Venga",
          "startFrame": 204
        }
      ],
      [
        {
          "text": "miradme",
          "startFrame": 213
        }
      ]
    ]
  },
  {
    "startFrame": 220,
    "endFrame": 240,
    "fontSize": 330,
    "top": 260,
    "lines": [
      [
        {
          "text": "bien",
          "startFrame": 220
        }
      ]
    ]
  },
  {
    "startFrame": 240,
    "endFrame": 260,
    "fontSize": 184,
    "top": 210,
    "lines": [
      [
        {
          "text": "Y",
          "startFrame": 240
        },
        {
          "text": "si",
          "startFrame": 248
        }
      ],
      [
        {
          "text": "vosotros",
          "startFrame": 250
        }
      ]
    ]
  },
  {
    "startFrame": 260,
    "endFrame": 285,
    "fontSize": 247,
    "top": 120,
    "lines": [
      [
        {
          "text": "no",
          "startFrame": 260
        }
      ],
      [
        {
          "text": "lo",
          "startFrame": 265
        },
        {
          "text": "veis",
          "startFrame": 268
        }
      ]
    ]
  },
  {
    "startFrame": 285,
    "endFrame": 293,
    "fontSize": 187,
    "top": 300,
    "lines": [
      [
        {
          "text": "vuestros",
          "startFrame": 285
        }
      ]
    ]
  },
  {
    "startFrame": 293,
    "endFrame": 328,
    "fontSize": 198,
    "top": 130,
    "lines": [
      [
        {
          "text": "clientes",
          "startFrame": 293
        }
      ],
      [
        {
          "text": "tampoco",
          "startFrame": 304
        }
      ]
    ]
  },
  {
    "startFrame": 338,
    "endFrame": 351,
    "fontSize": 189,
    "top": 270,
    "lines": [
      [
        {
          "text": "¿A",
          "startFrame": 338
        },
        {
          "text": "que",
          "startFrame": 346
        },
        {
          "text": "da",
          "startFrame": 348
        }
      ]
    ]
  },
  {
    "startFrame": 351,
    "endFrame": 373,
    "fontSize": 220,
    "top": 120,
    "lines": [
      [
        {
          "text": "que",
          "startFrame": 351
        }
      ],
      [
        {
          "text": "pensar?",
          "startFrame": 354
        }
      ]
    ]
  },
  {
    "startFrame": 373,
    "endFrame": 385,
    "fontSize": 177,
    "top": 280,
    "lines": [
      [
        {
          "text": "Comentad",
          "startFrame": 373
        }
      ]
    ]
  },
  {
    "startFrame": 385,
    "endFrame": 410,
    "fontSize": 162,
    "top": 170,
    "lines": [
      [
        {
          "text": "la",
          "startFrame": 385
        },
        {
          "text": "palabra",
          "startFrame": 389
        }
      ],
      [
        {
          "text": "fallo",
          "startFrame": 399
        }
      ]
    ]
  },
  {
    "startFrame": 410,
    "endFrame": 428,
    "fontSize": 207,
    "top": 120,
    "lines": [
      [
        {
          "text": "y",
          "startFrame": 410
        }
      ],
      [
        {
          "text": "os",
          "startFrame": 415
        },
        {
          "text": "envío",
          "startFrame": 419
        }
      ]
    ]
  },
  {
    "startFrame": 428,
    "endFrame": 457,
    "fontSize": 199,
    "top": 120,
    "lines": [
      [
        {
          "text": "la",
          "startFrame": 428
        },
        {
          "text": "guía",
          "startFrame": 437
        }
      ],
      [
        {
          "text": "paso",
          "startFrame": 444
        }
      ]
    ]
  },
  {
    "startFrame": 457,
    "endFrame": 480,
    "fontSize": 273,
    "top": 240,
    "lines": [
      [
        {
          "text": "a",
          "startFrame": 457
        },
        {
          "text": "paso",
          "startFrame": 462
        }
      ]
    ]
  },
  {
    "startFrame": 480,
    "endFrame": 502,
    "fontSize": 264,
    "top": 190,
    "lines": [
      [
        {
          "text": "Desde",
          "startFrame": 480
        }
      ],
      [
        {
          "text": "arriba",
          "startFrame": 489
        }
      ]
    ]
  },
  {
    "startFrame": 502,
    "endFrame": 521,
    "fontSize": 304,
    "top": 180,
    "lines": [
      [
        {
          "text": "desde",
          "startFrame": 502
        }
      ],
      [
        {
          "text": "abajo",
          "startFrame": 505
        }
      ]
    ]
  },
  {
    "startFrame": 521,
    "endFrame": 540,
    "fontSize": 226,
    "top": 140,
    "lines": [
      [
        {
          "text": "como",
          "startFrame": 521
        }
      ],
      [
        {
          "text": "queráis",
          "startFrame": 522
        }
      ]
    ]
  },
  {
    "startFrame": 540,
    "endFrame": 564,
    "fontSize": 270,
    "top": 120,
    "lines": [
      [
        {
          "text": "los",
          "startFrame": 540
        }
      ],
      [
        {
          "text": "moños",
          "startFrame": 544
        }
      ]
    ]
  },
  {
    "startFrame": 564,
    "endFrame": 588,
    "fontSize": 286,
    "top": 120,
    "lines": [
      [
        {
          "text": "la",
          "startFrame": 564
        }
      ],
      [
        {
          "text": "barba",
          "startFrame": 572
        }
      ]
    ]
  },
  {
    "startFrame": 588,
    "endFrame": 597,
    "fontSize": 233,
    "top": 120,
    "lines": [
      [
        {
          "text": "los",
          "startFrame": 588
        }
      ],
      [
        {
          "text": "dientes",
          "startFrame": 590
        }
      ]
    ]
  },
  {
    "startFrame": 597,
    "endFrame": 624,
    "fontSize": 278,
    "top": 150,
    "lines": [
      [
        {
          "text": "de",
          "startFrame": 597
        },
        {
          "text": "oro",
          "startFrame": 603
        }
      ],
      [
        {
          "text": "hasta",
          "startFrame": 617
        }
      ]
    ]
  },
  {
    "startFrame": 624,
    "endFrame": 653,
    "fontSize": 214,
    "top": 150,
    "lines": [
      [
        {
          "text": "los",
          "startFrame": 624
        }
      ],
      [
        {
          "text": "zapatos",
          "startFrame": 629
        }
      ]
    ]
  },
  {
    "startFrame": 653,
    "endFrame": 678,
    "fontSize": 164,
    "top": 140,
    "lines": [
      [
        {
          "text": "¿Veis",
          "startFrame": 653
        }
      ],
      [
        {
          "text": "algo",
          "startFrame": 657
        },
        {
          "text": "raro?",
          "startFrame": 661
        }
      ]
    ]
  },
  {
    "startFrame": 678,
    "endFrame": 699,
    "fontSize": 330,
    "top": 190,
    "lines": [
      [
        {
          "text": "Nada",
          "startFrame": 678
        }
      ]
    ]
  },
  {
    "startFrame": 701,
    "endFrame": 720,
    "fontSize": 191,
    "top": 230,
    "lines": [
      [
        {
          "text": "Os",
          "startFrame": 701
        },
        {
          "text": "lo",
          "startFrame": 703
        },
        {
          "text": "dije",
          "startFrame": 707
        }
      ]
    ]
  }
];
