"""Write the reel's jump-cut segments and corrected, remapped words as TS.

usage: make_reel_data.py cuts.json out.ts
"""
import json, re, sys

cuts_path, out_ts = sys.argv[1:3]
d = json.load(open(cuts_path))

# Whisper mishearings in this recording
FIX = {"Cloud": "Claude", "cloud.": "Claude.", "avío": "bio", "rils": "reels", "guión": "guion"}
words = []
for w in d["words"]:
    words.append({"text": FIX.get(w["text"], w["text"]), "start": w["start"], "end": w["end"]})
# "a gente" -> the comment keyword AGENTE
merged = []
for w in words:
    if merged and merged[-1]["text"] == "a" and w["text"] == "gente":
        merged[-1] = {"text": "AGENTE", "start": merged[-1]["start"], "end": w["end"]}
    else:
        merged.append(w)

# contextual fixes (previous word -> this word)
for i in range(1, len(merged)):
    prev, cur = merged[i - 1]["text"], merged[i]["text"]
    if cur == "bio" and prev == "el":
        merged[i - 1]["text"] = "la"
    if cur == "subir." and prev == "que":
        merged[i - 1]["text"] = "qué"
    if prev == "responde." and cur == "en":
        merged[i - 1]["text"] = "responde"

with open(out_ts, "w") as fh:
    fh.write("// Generated by make_reel_data.py from the transcript and jump-cut list.\n")
    fh.write("// SEGMENTS: [sourceStart, sourceEnd] seconds of k_joined.mp4 kept, in order.\n")
    fh.write("// WORDS: times in seconds on the edited timeline.\n\n")
    fh.write(f"export const DURATION = {d['duration']};\n\n")
    fh.write("export const SEGMENTS: [number, number][] = " + json.dumps(d["segments"]) + ";\n\n")
    fh.write("export const WORDS: { text: string; start: number; end: number }[] = " +
             json.dumps(merged, ensure_ascii=False, indent=1) + ";\n")
print(len(merged), "words,", len(d["segments"]), "segments,", d["duration"], "s")
print(" ".join(w["text"] for w in merged))
