// Generated by scripts/behind-captions/make_pages.py from the Whisper
// transcript and the person matte. Do not edit by hand.
export type Side = "left" | "right";
export type CaptionWord = { text: string; startFrame: number; side: Side; line: number };
export type CaptionPage = {
  startFrame: number;
  endFrame: number;
  fontSize: number;
  centerY: number;
  words: CaptionWord[];
};

export const PAGES: CaptionPage[] = [
  {
    "startFrame": 0,
    "endFrame": 12,
    "fontSize": 130,
    "centerY": 480,
    "words": [
      {
        "text": "VALE",
        "startFrame": 0,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 12,
    "endFrame": 25,
    "fontSize": 124,
    "centerY": 480,
    "words": [
      {
        "text": "DICEN",
        "startFrame": 12,
        "side": "left",
        "line": 0
      },
      {
        "text": "QUE",
        "startFrame": 21,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 25,
    "endFrame": 52,
    "fontSize": 130,
    "centerY": 480,
    "words": [
      {
        "text": "SOY",
        "startFrame": 25,
        "side": "left",
        "line": 0
      },
      {
        "text": "IA",
        "startFrame": 31,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 52,
    "endFrame": 62,
    "fontSize": 130,
    "centerY": 630,
    "words": [
      {
        "text": "PUES",
        "startFrame": 52,
        "side": "left",
        "line": 0
      },
      {
        "text": "OS",
        "startFrame": 58,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 62,
    "endFrame": 82,
    "fontSize": 130,
    "centerY": 630,
    "words": [
      {
        "text": "RETO",
        "startFrame": 62,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 82,
    "endFrame": 98,
    "fontSize": 62,
    "centerY": 570,
    "words": [
      {
        "text": "SI",
        "startFrame": 82,
        "side": "left",
        "line": 0
      },
      {
        "text": "ENCONTRÁIS",
        "startFrame": 85,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 98,
    "endFrame": 111,
    "fontSize": 112,
    "centerY": 540,
    "words": [
      {
        "text": "EL",
        "startFrame": 98,
        "side": "left",
        "line": 0
      },
      {
        "text": "FALLO",
        "startFrame": 101,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 111,
    "endFrame": 117,
    "fontSize": 130,
    "centerY": 540,
    "words": [
      {
        "text": "QUE",
        "startFrame": 111,
        "side": "left",
        "line": 0
      },
      {
        "text": "LO",
        "startFrame": 115,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 117,
    "endFrame": 135,
    "fontSize": 68,
    "centerY": 570,
    "words": [
      {
        "text": "DEMUESTRA",
        "startFrame": 117,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 135,
    "endFrame": 152,
    "fontSize": 102,
    "centerY": 550,
    "words": [
      {
        "text": "OS",
        "startFrame": 135,
        "side": "left",
        "line": 0
      },
      {
        "text": "SIGO",
        "startFrame": 146,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 152,
    "endFrame": 171,
    "fontSize": 69,
    "centerY": 530,
    "words": [
      {
        "text": "YO",
        "startFrame": 152,
        "side": "left",
        "line": 0
      },
      {
        "text": "A",
        "startFrame": 156,
        "side": "left",
        "line": 0
      },
      {
        "text": "VOSOTROS",
        "startFrame": 157,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 171,
    "endFrame": 179,
    "fontSize": 128,
    "centerY": 530,
    "words": [
      {
        "text": "OS",
        "startFrame": 171,
        "side": "left",
        "line": 0
      },
      {
        "text": "SIGO",
        "startFrame": 174,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 179,
    "endFrame": 204,
    "fontSize": 70,
    "centerY": 540,
    "words": [
      {
        "text": "YO",
        "startFrame": 179,
        "side": "left",
        "line": 0
      },
      {
        "text": "A",
        "startFrame": 181,
        "side": "left",
        "line": 0
      },
      {
        "text": "VOSOTROS",
        "startFrame": 184,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 204,
    "endFrame": 213,
    "fontSize": 130,
    "centerY": 610,
    "words": [
      {
        "text": "VENGA",
        "startFrame": 204,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 213,
    "endFrame": 220,
    "fontSize": 98,
    "centerY": 630,
    "words": [
      {
        "text": "MIRADME",
        "startFrame": 213,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 220,
    "endFrame": 240,
    "fontSize": 130,
    "centerY": 630,
    "words": [
      {
        "text": "BIEN",
        "startFrame": 220,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 240,
    "endFrame": 250,
    "fontSize": 130,
    "centerY": 630,
    "words": [
      {
        "text": "Y",
        "startFrame": 240,
        "side": "left",
        "line": 0
      },
      {
        "text": "SI",
        "startFrame": 248,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 250,
    "endFrame": 265,
    "fontSize": 82,
    "centerY": 650,
    "words": [
      {
        "text": "VOSOTROS",
        "startFrame": 250,
        "side": "left",
        "line": 0
      },
      {
        "text": "NO",
        "startFrame": 260,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 265,
    "endFrame": 285,
    "fontSize": 130,
    "centerY": 650,
    "words": [
      {
        "text": "LO",
        "startFrame": 265,
        "side": "left",
        "line": 0
      },
      {
        "text": "VEIS",
        "startFrame": 268,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 285,
    "endFrame": 293,
    "fontSize": 88,
    "centerY": 620,
    "words": [
      {
        "text": "VUESTROS",
        "startFrame": 285,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 293,
    "endFrame": 304,
    "fontSize": 88,
    "centerY": 620,
    "words": [
      {
        "text": "CLIENTES",
        "startFrame": 293,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 304,
    "endFrame": 328,
    "fontSize": 80,
    "centerY": 620,
    "words": [
      {
        "text": "TAMPOCO",
        "startFrame": 304,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 338,
    "endFrame": 348,
    "fontSize": 130,
    "centerY": 620,
    "words": [
      {
        "text": "¿A",
        "startFrame": 338,
        "side": "left",
        "line": 0
      },
      {
        "text": "QUE",
        "startFrame": 346,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 348,
    "endFrame": 373,
    "fontSize": 83,
    "centerY": 640,
    "words": [
      {
        "text": "DA",
        "startFrame": 348,
        "side": "left",
        "line": 0
      },
      {
        "text": "QUE",
        "startFrame": 351,
        "side": "left",
        "line": 0
      },
      {
        "text": "PENSAR?",
        "startFrame": 354,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 373,
    "endFrame": 389,
    "fontSize": 73,
    "centerY": 640,
    "words": [
      {
        "text": "COMENTAD",
        "startFrame": 373,
        "side": "left",
        "line": 0
      },
      {
        "text": "LA",
        "startFrame": 385,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 389,
    "endFrame": 399,
    "fontSize": 95,
    "centerY": 640,
    "words": [
      {
        "text": "PALABRA",
        "startFrame": 389,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 399,
    "endFrame": 415,
    "fontSize": 130,
    "centerY": 640,
    "words": [
      {
        "text": "FALLO",
        "startFrame": 399,
        "side": "left",
        "line": 0
      },
      {
        "text": "Y",
        "startFrame": 410,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 415,
    "endFrame": 428,
    "fontSize": 112,
    "centerY": 600,
    "words": [
      {
        "text": "OS",
        "startFrame": 415,
        "side": "left",
        "line": 0
      },
      {
        "text": "ENVÍO",
        "startFrame": 419,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 428,
    "endFrame": 444,
    "fontSize": 130,
    "centerY": 600,
    "words": [
      {
        "text": "LA",
        "startFrame": 428,
        "side": "left",
        "line": 0
      },
      {
        "text": "GUÍA",
        "startFrame": 437,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 444,
    "endFrame": 462,
    "fontSize": 130,
    "centerY": 600,
    "words": [
      {
        "text": "PASO",
        "startFrame": 444,
        "side": "left",
        "line": 0
      },
      {
        "text": "A",
        "startFrame": 457,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 462,
    "endFrame": 480,
    "fontSize": 130,
    "centerY": 600,
    "words": [
      {
        "text": "PASO",
        "startFrame": 462,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 480,
    "endFrame": 489,
    "fontSize": 130,
    "centerY": 590,
    "words": [
      {
        "text": "DESDE",
        "startFrame": 480,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 489,
    "endFrame": 502,
    "fontSize": 130,
    "centerY": 570,
    "words": [
      {
        "text": "ARRIBA",
        "startFrame": 489,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 502,
    "endFrame": 521,
    "fontSize": 130,
    "centerY": 560,
    "words": [
      {
        "text": "DESDE",
        "startFrame": 502,
        "side": "left",
        "line": 0
      },
      {
        "text": "ABAJO",
        "startFrame": 505,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 521,
    "endFrame": 540,
    "fontSize": 78,
    "centerY": 560,
    "words": [
      {
        "text": "COMO",
        "startFrame": 521,
        "side": "left",
        "line": 0
      },
      {
        "text": "QUERÁIS",
        "startFrame": 522,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 540,
    "endFrame": 564,
    "fontSize": 81,
    "centerY": 430,
    "words": [
      {
        "text": "LOS",
        "startFrame": 540,
        "side": "left",
        "line": 0
      },
      {
        "text": "MOÑOS",
        "startFrame": 544,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 564,
    "endFrame": 588,
    "fontSize": 130,
    "centerY": 430,
    "words": [
      {
        "text": "LA",
        "startFrame": 564,
        "side": "left",
        "line": 0
      },
      {
        "text": "BARBA",
        "startFrame": 572,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 588,
    "endFrame": 597,
    "fontSize": 130,
    "centerY": 530,
    "words": [
      {
        "text": "LOS",
        "startFrame": 588,
        "side": "left",
        "line": 0
      },
      {
        "text": "DIENTES",
        "startFrame": 590,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 597,
    "endFrame": 617,
    "fontSize": 130,
    "centerY": 530,
    "words": [
      {
        "text": "DE",
        "startFrame": 597,
        "side": "left",
        "line": 0
      },
      {
        "text": "ORO",
        "startFrame": 603,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 617,
    "endFrame": 629,
    "fontSize": 130,
    "centerY": 510,
    "words": [
      {
        "text": "HASTA",
        "startFrame": 617,
        "side": "left",
        "line": 0
      },
      {
        "text": "LOS",
        "startFrame": 624,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 629,
    "endFrame": 653,
    "fontSize": 123,
    "centerY": 510,
    "words": [
      {
        "text": "ZAPATOS",
        "startFrame": 629,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 653,
    "endFrame": 661,
    "fontSize": 130,
    "centerY": 510,
    "words": [
      {
        "text": "¿VEIS",
        "startFrame": 653,
        "side": "left",
        "line": 0
      },
      {
        "text": "ALGO",
        "startFrame": 657,
        "side": "right",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 661,
    "endFrame": 678,
    "fontSize": 130,
    "centerY": 510,
    "words": [
      {
        "text": "RARO?",
        "startFrame": 661,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 678,
    "endFrame": 699,
    "fontSize": 130,
    "centerY": 510,
    "words": [
      {
        "text": "NADA",
        "startFrame": 678,
        "side": "left",
        "line": 0
      }
    ]
  },
  {
    "startFrame": 701,
    "endFrame": 720,
    "fontSize": 130,
    "centerY": 510,
    "words": [
      {
        "text": "OS",
        "startFrame": 701,
        "side": "left",
        "line": 0
      },
      {
        "text": "LO",
        "startFrame": 703,
        "side": "right",
        "line": 0
      },
      {
        "text": "DIJE",
        "startFrame": 707,
        "side": "right",
        "line": 0
      }
    ]
  }
];
